name: TestsMSI

on:
  workflow_dispatch:
  push:
    branches:
    - master
    - 3.8
    - 3.7
    paths:
    - 'Tools/msi/**'
    - 'Lib/ensurepip/**'
  pull_request:
    branches:
    - master
    - 3.8
    - 3.7
    paths:
    - 'Tools/msi/**'
    - 'Lib/ensurepip/**'

jobs:
  build_win32:
    name: 'Windows (x86) Installer'
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install MSBuild 2015
      run: |
            Invoke-WebRequest -Uri https://download.microsoft.com/download/E/E/D/EEDF18A8-4AED-4CE0-BEBE-70A83094FC5A/BuildTools_Full.exe -OutFile BuildTools_Full.exe
            Start-Process -FilePath ./BuildTools_Full.exe -ArgumentList "/InstallSelectableItems", "Microsoft.VisualStudio.Component.VC.140", "/quiet", "/norestart", "/force" -Wait -PassThru
    - name: Build CPython installer
      run: .\Tools\msi\build.bat -x86

  build_win_amd64:
    name: 'Windows (x64) Installer'
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install MSBuild 2015
      run: |
            Invoke-WebRequest -Uri https://download.microsoft.com/download/E/E/D/EEDF18A8-4AED-4CE0-BEBE-70A83094FC5A/BuildTools_Full.exe -OutFile BuildTools_Full.exe
            Start-Process -FilePath ./BuildTools_Full.exe -ArgumentList "/InstallSelectableItems", "Microsoft.VisualStudio.Component.VC.140", "/quiet", "/norestart", "/force" -Wait -PassThru
    - name: Build CPython installer
      run: .\Tools\msi\build.bat -x64
